{% set name = "hapiclient" %}
{% set version = "0.2.8" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hapiclient-{{ version }}.tar.gz
  sha256: 849e646a5ed3d60d0f39413b224afe6a30278f8ebfcbde123167a4123d85aa33

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - isodate >=0.6.0
    - urllib3
    - joblib
    - pandas >=0.23
    - numpy >=1.14.3

test:
  imports:
    - hapiclient
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://pypi.python.org/pypi/hapiclient/
  summary: Interface to Heliophysics data server API
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dstansby
